import { ExternalLink, Link2, UserRound } from "lucide-react";
import { authApi, usersApi } from "../lib/api";
import { useState } from "react";
import { useResource } from "../lib/use-resource";
import { Btn, Mono, PageFade } from "../components/primitives";
import { TopBar } from "../components/TopBar";

export function SettingsPage() {
  const user = useResource(() => usersApi.profile()); const providers = useResource(() => usersApi.providers()); const [name, setName] = useState(""); const [note, setNote] = useState<string | null>(null);
  const save = async () => { try { await usersApi.updateProfile(name || user.data?.fullName || ""); setNote("Profile saved."); void user.refresh(); } catch (err) { setNote(err instanceof Error ? err.message : "Could not save profile"); } };
  const disconnect = async (provider: string) => { try { await usersApi.disconnectProvider(provider); void providers.refresh(); } catch (err) { setNote(err instanceof Error ? err.message : "Could not disconnect provider"); } };
  return <PageFade><TopBar title="Settings"/><div className="saas-page max-w-5xl space-y-5"><section className="hero-grid rounded-3xl p-7"><p className="eyebrow">Account preferences</p><h1 className="mt-3 text-3xl font-semibold">Your operating profile</h1><p className="mt-2 text-sm text-muted-foreground">Manage your profile and connected developer accounts.</p></section><section className="glass-panel"><Header icon={UserRound} title="Profile" text="Identity used across your workspace."/>{user.error ? <p className="p-5 text-sm text-destructive">{user.error}</p> : <div className="p-5"><div className="flex gap-4 items-center"><div className="avatar-glow text-lg">{user.data?.fullName?.slice(0,1) || "?"}</div><div><p className="font-medium">{user.data?.fullName || "Loading…"}</p><p className="mt-1 text-sm text-muted-foreground">{user.data?.email}</p></div></div><label className="block text-xs text-muted-foreground mt-5 max-w-lg">Display name<input value={name || user.data?.fullName || ""} onChange={e => setName(e.target.value)} className="saas-input mt-1.5"/></label><div className="mt-3 max-w-lg flex justify-between items-center"><Mono className="text-primary">@{user.data?.username}</Mono><Btn onClick={() => void save()}>Save changes</Btn></div>{note && <p className="text-xs text-muted-foreground mt-3">{note}</p>}</div>}</section><section className="glass-panel"><Header icon={Link2} title="Connected accounts" text="Use a provider to sign in quickly and connect your developer identity."/><div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-white/[.06]">{["github", "google"].map(provider => <Provider key={provider} name={provider === "github" ? "GitHub" : "Google"} description={providers.data?.some(p => p.provider === provider) ? "Connected to your account" : "Not connected"} href={provider === "github" ? authApi.githubLoginUrl() : authApi.googleLoginUrl()} connected={providers.data?.some(p => p.provider === provider)} onDisconnect={() => void disconnect(provider)}/>)}</div></section></div></PageFade>;
}
function Header({ icon: Icon, title, text }: { icon: typeof UserRound; title: string; text: string }) { return <div className="px-5 py-4 border-b border-white/[.06] flex gap-3 items-center"><span className="metric-icon"><Icon className="w-4 h-4"/></span><div><h2 className="text-sm font-semibold">{title}</h2><p className="text-[11px] text-muted-foreground mt-0.5">{text}</p></div></div>; }
function Provider({ name, description, href, connected, onDisconnect }: { name: string; description: string; href: string; connected?: boolean; onDisconnect: () => void }) { return <div className="p-5 flex justify-between gap-4 items-center"><div><p className="font-medium text-sm">{name}</p><p className="text-xs text-muted-foreground mt-1">{description}</p></div>{connected ? <Btn variant="danger" onClick={onDisconnect}>Disconnect</Btn> : <a href={href}><Btn variant="secondary">Connect <ExternalLink className="w-3.5 h-3.5"/></Btn></a>}</div>; }
