import { useState, useEffect, useCallback } from "react";
import { CheckCircle2, CircleDashed, Clock3, GitBranch, Hash, RotateCcw, Terminal, User, XCircle, Zap } from "lucide-react";
import type { NavState } from "../lib/types";
import { PageFade, Btn, Mono, StatusBadge } from "../components/primitives";
import { TopBar } from "../components/TopBar";
import { deploymentsApi, type Deployment, type DeploymentLog } from "../lib/deploymentsApi";
import { deploymentStatusToUi, formatRelativeTime, formatDuration } from "../lib/statusMap";

export function DeploymentPage({ projectId, deploymentId, onNav }: { projectId: string; deploymentId: string; onNav: (s: NavState) => void }) {
  const [dep, setDep] = useState<Deployment | null>(null); const [logs, setLogs] = useState<DeploymentLog[]>([]); const [loading, setLoading] = useState(true); const [redeploying, setRedeploying] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const result = await deploymentsApi.get(deploymentId); setDep(result); setLogs(await deploymentsApi.logs(deploymentId)); } catch (err) { setError(err instanceof Error ? err.message : "Failed to load deployment"); } finally { setLoading(false); } }, [deploymentId]);
  useEffect(() => { load(); const id = setInterval(() => { if (dep && ["QUEUED", "RUNNING"].includes(dep.status)) load(); }, 3000); return () => clearInterval(id); }, [load, dep]);
  async function redeploy() { setRedeploying(true); try { const next = await deploymentsApi.trigger(projectId, { branch: dep?.branch, commitMessage: dep?.commitMessage }); onNav({ page: "deployment", projectId, deploymentId: next.id }); } catch (err) { setError(err instanceof Error ? err.message : "Failed to redeploy"); } finally { setRedeploying(false); } }
  if (loading) return <PageFade><TopBar title="Loading…" crumbs={[{ label: "Projects", nav: { page: "dashboard" } }]} onCrumb={onNav} onNav={onNav} /><div className="p-6 text-sm text-muted-foreground">Establishing deployment telemetry…</div></PageFade>;
  if (error || !dep) return <PageFade><TopBar title="Deployment" onNav={onNav} /><div className="p-6 text-sm text-destructive">{error ?? "Deployment not found"}</div></PageFade>;
  const running = dep.status === "RUNNING" || dep.status === "QUEUED"; const succeeded = dep.status === "SUCCESS"; const projectName = dep.environment?.project?.name ?? "Project";
  const stages = [{ label: "Queued", complete: true }, { label: "Build", complete: dep.status !== "QUEUED" }, { label: "Release", complete: succeeded }, { label: "Live", complete: succeeded }];
  return <PageFade><TopBar title="Deployment run" crumbs={[{ label: "Projects", nav: { page: "dashboard" } }, { label: projectName, nav: { page: "project", projectId } }]} onCrumb={onNav} onNav={onNav} />
    <div className="p-6 max-w-6xl space-y-6">
      <section className="relative overflow-hidden rounded-3xl border border-border bg-card surface-glow px-6 py-7"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_top_right,rgba(91,153,255,.18),transparent_65%)]" />
        <div className="relative flex items-start justify-between gap-5 flex-wrap"><div><div className="flex gap-3 items-center mb-4"><StatusBadge status={deploymentStatusToUi(dep.status)} pulse={running} /><Mono className="text-muted-foreground">run_{dep.id.slice(0, 8)}</Mono></div><h1 className="text-2xl font-bold font-display text-foreground">{dep.commitMessage}</h1><div className="flex flex-wrap gap-x-5 gap-y-2 mt-4 text-xs text-muted-foreground"><span className="flex gap-1.5 items-center"><Hash className="w-3.5 h-3.5" /><Mono>{dep.commitSha.slice(0, 7)}</Mono></span><span className="flex gap-1.5 items-center"><GitBranch className="w-3.5 h-3.5" />{dep.branch}</span><span className="flex gap-1.5 items-center"><User className="w-3.5 h-3.5" />{dep.triggeredBy?.fullName ?? "Unknown"}</span><span className="flex gap-1.5 items-center"><Clock3 className="w-3.5 h-3.5" />{formatRelativeTime(dep.createdAt)}</span></div></div>{dep.status === "FAILED" && <Btn onClick={redeploy} disabled={redeploying}><RotateCcw className="w-4 h-4" />{redeploying ? "Queuing…" : "Redeploy"}</Btn>}</div>
        <div className="relative grid grid-cols-4 mt-8 pt-5 border-t border-border">{stages.map((stage, index) => <div key={stage.label} className="relative flex flex-col gap-2"><div className="flex items-center">{stage.complete ? <CheckCircle2 className="w-5 h-5 text-[#5ee3a1]" /> : dep.status === "FAILED" && index === 2 ? <XCircle className="w-5 h-5 text-destructive" /> : <CircleDashed className={"w-5 h-5 " + (running ? "text-primary animate-spin" : "text-muted-foreground")} />}{index < 3 && <span className={"h-px flex-1 mx-2 " + (stage.complete ? "bg-[#5ee3a1]/60" : "bg-border")} />}</div><span className={stage.complete ? "text-xs font-semibold text-foreground" : "text-xs text-muted-foreground"}>{stage.label}</span></div>)}</div>
      </section>
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-6"><section className="rounded-2xl bg-[#07101f] border border-[#263650] overflow-hidden surface-glow"><div className="flex items-center gap-2 px-5 py-4 border-b border-[#263650]"><Terminal className="w-4 h-4 text-[#69d7ff]" /><span className="text-sm font-semibold text-white">Build output</span><span className="ml-auto text-[11px] text-[#91a0bb]">{logs.length} events</span></div><div className="p-5 font-mono text-xs leading-6 min-h-[260px] max-h-[420px] overflow-auto">{logs.length ? logs.map(log => <div key={log.id} className="flex gap-3"><span className="text-[#64748b] shrink-0">{new Date(log.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span><span className={log.logLevel === "ERROR" ? "text-[#ff8290]" : log.logLevel === "WARNING" ? "text-[#f8c76b]" : "text-[#cbd7ec]"}>{log.message}</span></div>) : <span className="text-[#91a0bb]">Waiting for the runner to emit logs…</span>}</div></section>
        <aside className="space-y-4"><div className="rounded-2xl bg-card border border-border p-5 surface-glow"><p className="text-xs text-muted-foreground">Duration</p><p className="font-mono text-xl font-semibold mt-1">{dep.duration != null ? formatDuration(dep.duration) : "In progress"}</p></div><div className="rounded-2xl bg-card border border-border p-5 surface-glow"><p className="text-xs text-muted-foreground">Environment</p><p className="font-semibold text-sm mt-2">{dep.environment?.name ?? "Production"}</p><p className="font-mono text-xs text-muted-foreground mt-1 truncate">{dep.environment?.domain ?? "No domain configured"}</p></div><div className="rounded-2xl bg-accent/60 border border-primary/15 p-5"><Zap className="w-4 h-4 text-accent-foreground mb-3" /><p className="text-sm font-semibold">Live deployment telemetry</p><p className="text-xs text-muted-foreground mt-1.5">This screen refreshes while the run is active.</p></div></aside></div>
    </div></PageFade>;
}
