import { useState } from "react";
import { motion } from "motion/react";
import { Activity, ArrowUpRight, Eye, EyeOff, Github, ShieldCheck, Sparkles } from "lucide-react";
import { Field, Btn } from "../components/primitives";
import { useAuth } from "../lib/AuthContext";
import { authApi } from "../lib/api";

function GoogleMark() { return <svg viewBox="0 0 24 24" className="w-4 h-4"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.99 5.99 0 0 1-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09Z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23Z"/><path fill="#FBBC05" d="M5.84 14.09A6.98 6.98 0 0 1 5.49 12c0-.73.13-1.43.35-2.09V7.07H2.18A11 11 0 0 0 1 12c0 1.78.43 3.45 1.18 4.93l3.66-2.84Z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84C6.71 7.31 9.14 5.38 12 5.38Z"/></svg>; }

export function LoginPage() {
  const { login, register, loading, error } = useAuth();
  const [email, setEmail] = useState(""); const [pw, setPw] = useState(""); const [username, setUsername] = useState(""); const [fullName, setFullName] = useState(""); const [show, setShow] = useState(false); const [mode, setMode] = useState<"login" | "signup">("login");
  async function submit(e: React.FormEvent) { e.preventDefault(); try { mode === "login" ? await login(email, pw) : await register({ email, username, password: pw, fullName }); } catch { /* context renders the error */ } }
  return <div className="min-h-screen bg-[#080d1c] flex items-center justify-center px-4 relative overflow-hidden"><div className="absolute -top-32 -left-20 w-[36rem] h-[36rem] rounded-full bg-[#665cff]/25 blur-[120px]" /><div className="absolute -bottom-36 -right-20 w-[34rem] h-[34rem] rounded-full bg-[#23c7ff]/15 blur-[120px]" />
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35, ease: "easeOut" }} className="w-full max-w-5xl grid md:grid-cols-[1.05fr_.95fr] rounded-3xl overflow-hidden border border-white/10 bg-[#10182c]/85 shadow-2xl shadow-black/40 backdrop-blur-xl">
      <div className="hidden md:flex flex-col p-10 bg-[linear-gradient(145deg,#1d2360,#10314f_60%,#10182c)] relative overflow-hidden text-white"><div className="absolute -right-12 -top-12 w-64 h-64 bg-[#837bff]/35 rounded-full blur-3xl" /><div className="relative flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-[#38c9ff] grid place-items-center shadow-lg shadow-primary/40"><Activity className="w-5 h-5 text-white" /></div><div><p className="font-bold">BuildMonitor</p><p className="text-[10px] uppercase tracking-[.16em] text-[#a9c9ee]">Control plane</p></div></div><div className="relative my-auto"><div className="flex items-center gap-2 text-[#8bdbff] text-xs uppercase tracking-[.18em] font-semibold"><Sparkles className="w-3.5 h-3.5" /> Release intelligence</div><h1 className="text-4xl font-bold font-display leading-tight mt-4">See every signal.<br />Ship with confidence.</h1><p className="text-[#c6d5f0] text-sm leading-6 mt-5 max-w-sm">A calm command center for deployments, reliability, and the work that keeps your services moving.</p></div><div className="relative flex items-center gap-3 text-xs text-[#b5c7e8]"><ShieldCheck className="w-4 h-4 text-[#67e5ae]" /> Secure session management · Built for teams</div></div>
      <div className="p-7 sm:p-10"><div className="mb-7"><div className="md:hidden w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-[#38c9ff] grid place-items-center mb-5"><Activity className="w-5 h-5 text-white" /></div><p className="text-xs font-semibold tracking-[.14em] uppercase text-accent-foreground">Welcome back</p><h1 className="text-2xl font-bold text-foreground mt-2 font-display">{mode === "login" ? "Sign in to your workspace" : "Create your workspace"}</h1><p className="text-sm text-muted-foreground mt-2">{mode === "login" ? "Continue where your last deployment left off." : "Start monitoring releases in minutes."}</p></div>
        <div className="space-y-2.5 mb-5"><a href={authApi.githubLoginUrl()} className="w-full flex items-center justify-center gap-2.5 px-4 py-2.5 border border-border rounded-xl text-sm font-semibold text-foreground hover:bg-secondary transition-colors"><Github className="w-4 h-4" />Continue with GitHub</a><a href={authApi.googleLoginUrl()} className="w-full flex items-center justify-center gap-2.5 px-4 py-2.5 border border-border rounded-xl text-sm font-semibold text-foreground hover:bg-secondary transition-colors"><GoogleMark />Continue with Google</a></div>
        <div className="relative mb-5"><div className="absolute inset-0 flex items-center"><div className="w-full border-t border-border" /></div><div className="relative flex justify-center"><span className="bg-card px-3 text-xs text-muted-foreground">or continue with email</span></div></div>
        <form className="space-y-4" onSubmit={submit}>{mode === "signup" && <><Field label="Full name" placeholder="Ada Lovelace" value={fullName} onChange={setFullName} /><Field label="Username" placeholder="ada" value={username} onChange={setUsername} /></>}<Field label="Email address" type="email" placeholder="you@company.com" value={email} onChange={setEmail} /><Field label="Password" type={show ? "text" : "password"} placeholder="••••••••" value={pw} onChange={setPw} right={<button type="button" onClick={() => setShow(v => !v)} className="text-muted-foreground hover:text-foreground">{show ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button>} />{error && <p className="text-sm text-destructive">{error}</p>}<Btn type="submit" className="w-full justify-center py-2.5" disabled={loading}>{loading ? "Please wait…" : <>{mode === "login" ? "Sign in" : "Create account"}<ArrowUpRight className="w-4 h-4" /></>}</Btn></form>
        <p className="text-center text-sm text-muted-foreground mt-6">{mode === "login" ? "Don't have an account? " : "Already have an account? "}<button onClick={() => setMode(m => m === "login" ? "signup" : "login")} className="text-primary hover:underline font-semibold">{mode === "login" ? "Sign up" : "Sign in"}</button></p>
      </div>
    </motion.div>
  </div>;
}
